---
apiVersion: v1
kind: Pod
metadata:
  name: dov-bear
  labels:
    app: dov-bear
  namespace: myns
spec:
  containers:
    - name: dov-bear-container
      image: chukmunnlee/dov-bear:v1
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: '5000'
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      ports:
        - containerPort: 5000
