apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"dev-ns"}}
    creationTimestamp: "2025-11-13T03:10:24Z"
    labels:
      env: dev
      kubernetes.io/metadata.name: dev-ns
    name: dev-ns
    resourceVersion: "623646"
    uid: f89955d0-9c52-40e2-88a4-069b10622c9c
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  data:
    INSTANCE_NAME: Z2VuZXJhdGVkIGZyb20ga3VzdG9taXpl
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"INSTANCE_NAME":"Z2VuZXJhdGVkIGZyb20ga3VzdG9taXpl"},"kind":"Secret","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"wam-dov-secret-7m9hm84b5k","namespace":"dev-ns"},"type":"Opaque"}
    creationTimestamp: "2025-11-13T03:10:24Z"
    labels:
      env: dev
    name: wam-dov-secret-7m9hm84b5k
    namespace: dev-ns
    resourceVersion: "623649"
    uid: 65b7cfd0-d34f-43f3-a76c-50bff3f2ae79
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev"},"name":"wam-dov-svc","namespace":"dev-ns"},"spec":{"ports":[{"port":80,"targetPort":5000}],"selector":{"app":"dov-bear","dept":"eng","env":"dev"},"type":"ClusterIP"}}
    creationTimestamp: "2025-11-13T03:10:24Z"
    labels:
      app: dov
      env: dev
    name: wam-dov-svc
    namespace: dev-ns
    resourceVersion: "623652"
    uid: 741a2f36-fbde-4379-b83c-8223f97ff301
  spec:
    clusterIP: 10.109.13.121
    clusterIPs:
    - 10.109.13.121
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: dov-bear
      dept: eng
      env: dev
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dov","env":"dev"},"name":"wam-dov-deploy","namespace":"dev-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"dov-bear","dept":"eng","env":"dev"}},"template":{"metadata":{"labels":{"app":"dov-bear","dept":"eng","env":"dev"},"name":"dov-bear","namespace":"myns"},"spec":{"containers":[{"env":[{"name":"PORT","value":"5000"},{"name":"INSTANCE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"INSTANCE_HASH","valueFrom":{"secretKeyRef":{"key":"INSTANCE_NAME","name":"wam-dov-secret-7m9hm84b5k"}}}],"image":"chukmunnlee/dov-bear:v1","imagePullPolicy":"IfNotPresent","name":"dov-bear-container","ports":[{"containerPort":5000}]}]}}}}
    creationTimestamp: "2025-11-13T03:10:24Z"
    generation: 2
    labels:
      app: dov
      env: dev
    name: wam-dov-deploy
    namespace: dev-ns
    resourceVersion: "624191"
    uid: 455811f9-5420-4abf-8800-f374aeb20c83
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: dov-bear
        dept: eng
        env: dev
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: dov-bear
          dept: eng
          env: dev
        name: dov-bear
        namespace: myns
      spec:
        containers:
        - env:
          - name: PORT
            value: "5000"
          - name: INSTANCE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: INSTANCE_HASH
            valueFrom:
              secretKeyRef:
                key: INSTANCE_NAME
                name: wam-dov-secret-7m9hm84b5k
          image: chukmunnlee/dov-bear:v1
          imagePullPolicy: IfNotPresent
          name: dov-bear-container
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-11-13T03:12:30Z"
      lastUpdateTime: "2025-11-13T03:12:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2025-11-13T03:10:24Z"
      lastUpdateTime: "2025-11-13T03:12:30Z"
      message: ReplicaSet "wam-dov-deploy-d465bd5f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
