---
apiVersion: v1
kind: Namespace
metadata:
  name: cadang-ns
  labels:
    dept: eng
    app: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadang-deploy
  namespace: cadang-ns
  labels:
    app: caddy-dov
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 30%
  selector:
    matchLabels:
      name: caddy-dov-bear-po
      app: caddy-dov-bear
      dept: eng
  template:
    metadata:
      labels:
        name: caddy-dov-bear-po
        app: caddy-dov-bear
        dept: eng
    spec:
      containers:
        - name: caddy-dov-bear-container
          image: chukmunnlee/cfdsa-workshop02:v1.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: web-port
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cadang-svc
  namespace: cadang-ns
  labels:
    app: caddy-dov
spec:
  type: LoadBalancer
  selector:
    app: caddy-dov-bear
    name: caddy-dov-bear-po
    dept: eng
  ports:
    - port: 80
      targetPort: web-port
